sonar.organization=aspirebrian-lab
sonar.projectKey=aspirebrian-lab_PenPall
sonar.projectName=PenPall
sonar.host.url=https://sonarcloud.io

sonar.sources=writers-companion-app/client/src,writers-companion-app/server/src
sonar.tests=writers-companion-app/client/src
sonar.test.inclusions=**/*.test.ts,**/*.test.tsx
sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/coverage/**

sonar.sourceEncoding=UTF-8